FROM postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD qwerty
ENV POSTGRES_DB vlog

#
#CMD "psql -U postgres -d vlog"

#
#FROM openjdk:11
#COPY ./target/backend-0.0.1-SNAPSHOT.jar /app/backend.jar
#CMD ["java", "-jar", "/app/backend.jar"]
